### ISSUE TITLE
Add license information to JavaScript

### ISSUE THREAD

**Issue by MasterOfTheTiger** [diaspora/sharetodiaspora#3]
Add [license information](https://www.gnu.org/software/librejs/) about all the Javascript used by Share to Diaspora* so that it is compatible with LibreJS. Otherwise LibreJS will think that this is non free javascript. 

I would be willing to work on it, but I need to know what method should be used to implement this.

**Comment by skyschub** [comment]
Any method that does neither create unnecessary comments in JS files nor require additional HTML markup will do.

**Comment by MasterOfTheTiger** [comment]
Does the JavaScript web labels solution work? https://www.gnu.org/software/librejs/free-your-javascript.html those are the methods that work with LibreJS.

**Comment by MasterOfTheTiger** [comment]
Ah. We're you being sarcastic? It seems that you need either comments in JS or HTML markup to do it.
